version: '3'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: dbname
      MYSQL_PASSWORD: playground
      MYSQL_USER: sqlx
    ports:
    - 3306:3306
    volumes:
    - ./data:/docker-entrypoint-initdb.d:ro
